// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hellochain33.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	hellochain33.proto

It has these top-level messages:
	Hellochain33Action
	SetSelfIntroAction
	LogSetSelfIntro
	PingPongAction
	LogPingPong
	SelfIntroInfo
	PingPongStatus
	ReqPingPongStatus
	PingPongCount
	ReqAccount
	ReqAccountSpecified
	ResAccountsSelfIntro
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hellochain33Action struct {
	// Types that are valid to be assigned to Value:
	//	*Hellochain33Action_SetSelfIntro
	//	*Hellochain33Action_PingPong
	Value isHellochain33Action_Value `protobuf_oneof:"value"`
	Ty    int32                      `protobuf:"varint,3,opt,name=ty" json:"ty,omitempty"`
}

func (m *Hellochain33Action) Reset()                    { *m = Hellochain33Action{} }
func (m *Hellochain33Action) String() string            { return proto.CompactTextString(m) }
func (*Hellochain33Action) ProtoMessage()               {}
func (*Hellochain33Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isHellochain33Action_Value interface {
	isHellochain33Action_Value()
}

type Hellochain33Action_SetSelfIntro struct {
	SetSelfIntro *SetSelfIntroAction `protobuf:"bytes,1,opt,name=SetSelfIntro,oneof"`
}
type Hellochain33Action_PingPong struct {
	PingPong *PingPongAction `protobuf:"bytes,2,opt,name=PingPong,oneof"`
}

func (*Hellochain33Action_SetSelfIntro) isHellochain33Action_Value() {}
func (*Hellochain33Action_PingPong) isHellochain33Action_Value()     {}

func (m *Hellochain33Action) GetValue() isHellochain33Action_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Hellochain33Action) GetSetSelfIntro() *SetSelfIntroAction {
	if x, ok := m.GetValue().(*Hellochain33Action_SetSelfIntro); ok {
		return x.SetSelfIntro
	}
	return nil
}

func (m *Hellochain33Action) GetPingPong() *PingPongAction {
	if x, ok := m.GetValue().(*Hellochain33Action_PingPong); ok {
		return x.PingPong
	}
	return nil
}

func (m *Hellochain33Action) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Hellochain33Action) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Hellochain33Action_OneofMarshaler, _Hellochain33Action_OneofUnmarshaler, _Hellochain33Action_OneofSizer, []interface{}{
		(*Hellochain33Action_SetSelfIntro)(nil),
		(*Hellochain33Action_PingPong)(nil),
	}
}

func _Hellochain33Action_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Hellochain33Action)
	// value
	switch x := m.Value.(type) {
	case *Hellochain33Action_SetSelfIntro:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetSelfIntro); err != nil {
			return err
		}
	case *Hellochain33Action_PingPong:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PingPong); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Hellochain33Action.Value has unexpected type %T", x)
	}
	return nil
}

func _Hellochain33Action_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Hellochain33Action)
	switch tag {
	case 1: // value.SetSelfIntro
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SetSelfIntroAction)
		err := b.DecodeMessage(msg)
		m.Value = &Hellochain33Action_SetSelfIntro{msg}
		return true, err
	case 2: // value.PingPong
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PingPongAction)
		err := b.DecodeMessage(msg)
		m.Value = &Hellochain33Action_PingPong{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Hellochain33Action_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Hellochain33Action)
	// value
	switch x := m.Value.(type) {
	case *Hellochain33Action_SetSelfIntro:
		s := proto.Size(x.SetSelfIntro)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Hellochain33Action_PingPong:
		s := proto.Size(x.PingPong)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SetSelfIntroAction struct {
	Introduction string `protobuf:"bytes,1,opt,name=introduction" json:"introduction,omitempty"`
	Age          int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Male         bool   `protobuf:"varint,3,opt,name=male" json:"male,omitempty"`
	Married      bool   `protobuf:"varint,4,opt,name=married" json:"married,omitempty"`
	Notes        string `protobuf:"bytes,5,opt,name=notes" json:"notes,omitempty"`
}

func (m *SetSelfIntroAction) Reset()                    { *m = SetSelfIntroAction{} }
func (m *SetSelfIntroAction) String() string            { return proto.CompactTextString(m) }
func (*SetSelfIntroAction) ProtoMessage()               {}
func (*SetSelfIntroAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SetSelfIntroAction) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *SetSelfIntroAction) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *SetSelfIntroAction) GetMale() bool {
	if m != nil {
		return m.Male
	}
	return false
}

func (m *SetSelfIntroAction) GetMarried() bool {
	if m != nil {
		return m.Married
	}
	return false
}

func (m *SetSelfIntroAction) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type LogSetSelfIntro struct {
	Addr     string              `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Previous *SetSelfIntroAction `protobuf:"bytes,2,opt,name=previous" json:"previous,omitempty"`
	Current  *SetSelfIntroAction `protobuf:"bytes,3,opt,name=current" json:"current,omitempty"`
}

func (m *LogSetSelfIntro) Reset()                    { *m = LogSetSelfIntro{} }
func (m *LogSetSelfIntro) String() string            { return proto.CompactTextString(m) }
func (*LogSetSelfIntro) ProtoMessage()               {}
func (*LogSetSelfIntro) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogSetSelfIntro) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *LogSetSelfIntro) GetPrevious() *SetSelfIntroAction {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *LogSetSelfIntro) GetCurrent() *SetSelfIntroAction {
	if m != nil {
		return m.Current
	}
	return nil
}

type PingPongAction struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Notes   string `protobuf:"bytes,2,opt,name=notes" json:"notes,omitempty"`
}

func (m *PingPongAction) Reset()                    { *m = PingPongAction{} }
func (m *PingPongAction) String() string            { return proto.CompactTextString(m) }
func (*PingPongAction) ProtoMessage()               {}
func (*PingPongAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PingPongAction) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PingPongAction) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type LogPingPong struct {
	Addr     string          `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Previous *PingPongStatus `protobuf:"bytes,2,opt,name=previous" json:"previous,omitempty"`
	Current  *PingPongStatus `protobuf:"bytes,3,opt,name=current" json:"current,omitempty"`
}

func (m *LogPingPong) Reset()                    { *m = LogPingPong{} }
func (m *LogPingPong) String() string            { return proto.CompactTextString(m) }
func (*LogPingPong) ProtoMessage()               {}
func (*LogPingPong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogPingPong) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *LogPingPong) GetPrevious() *PingPongStatus {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *LogPingPong) GetCurrent() *PingPongStatus {
	if m != nil {
		return m.Current
	}
	return nil
}

type SelfIntroInfo struct {
	Introduction string `protobuf:"bytes,1,opt,name=introduction" json:"introduction,omitempty"`
	Age          int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Male         bool   `protobuf:"varint,3,opt,name=male" json:"male,omitempty"`
	Married      bool   `protobuf:"varint,4,opt,name=married" json:"married,omitempty"`
}

func (m *SelfIntroInfo) Reset()                    { *m = SelfIntroInfo{} }
func (m *SelfIntroInfo) String() string            { return proto.CompactTextString(m) }
func (*SelfIntroInfo) ProtoMessage()               {}
func (*SelfIntroInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SelfIntroInfo) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *SelfIntroInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *SelfIntroInfo) GetMale() bool {
	if m != nil {
		return m.Male
	}
	return false
}

func (m *SelfIntroInfo) GetMarried() bool {
	if m != nil {
		return m.Married
	}
	return false
}

// true:ping; false: pong
type PingPongStatus struct {
	Status bool `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *PingPongStatus) Reset()                    { *m = PingPongStatus{} }
func (m *PingPongStatus) String() string            { return proto.CompactTextString(m) }
func (*PingPongStatus) ProtoMessage()               {}
func (*PingPongStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PingPongStatus) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ReqPingPongStatus struct {
	Status bool `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *ReqPingPongStatus) Reset()                    { *m = ReqPingPongStatus{} }
func (m *ReqPingPongStatus) String() string            { return proto.CompactTextString(m) }
func (*ReqPingPongStatus) ProtoMessage()               {}
func (*ReqPingPongStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReqPingPongStatus) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type PingPongCount struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count"`
}

func (m *PingPongCount) Reset()                    { *m = PingPongCount{} }
func (m *PingPongCount) String() string            { return proto.CompactTextString(m) }
func (*PingPongCount) ProtoMessage()               {}
func (*PingPongCount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PingPongCount) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReqAccount struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *ReqAccount) Reset()                    { *m = ReqAccount{} }
func (m *ReqAccount) String() string            { return proto.CompactTextString(m) }
func (*ReqAccount) ProtoMessage()               {}
func (*ReqAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ReqAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type ReqAccountSpecified struct {
	// Types that are valid to be assigned to Value:
	//	*ReqAccountSpecified_GreaterThan
	//	*ReqAccountSpecified_NotgreaterThan
	//	*ReqAccountSpecified_Male
	//	*ReqAccountSpecified_Married
	Value isReqAccountSpecified_Value `protobuf_oneof:"value"`
	Ty    int32                       `protobuf:"varint,5,opt,name=ty" json:"ty,omitempty"`
}

func (m *ReqAccountSpecified) Reset()                    { *m = ReqAccountSpecified{} }
func (m *ReqAccountSpecified) String() string            { return proto.CompactTextString(m) }
func (*ReqAccountSpecified) ProtoMessage()               {}
func (*ReqAccountSpecified) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type isReqAccountSpecified_Value interface {
	isReqAccountSpecified_Value()
}

type ReqAccountSpecified_GreaterThan struct {
	GreaterThan int32 `protobuf:"varint,1,opt,name=greaterThan,oneof"`
}
type ReqAccountSpecified_NotgreaterThan struct {
	NotgreaterThan int32 `protobuf:"varint,2,opt,name=notgreaterThan,oneof"`
}
type ReqAccountSpecified_Male struct {
	Male bool `protobuf:"varint,3,opt,name=male,oneof"`
}
type ReqAccountSpecified_Married struct {
	Married bool `protobuf:"varint,4,opt,name=married,oneof"`
}

func (*ReqAccountSpecified_GreaterThan) isReqAccountSpecified_Value()    {}
func (*ReqAccountSpecified_NotgreaterThan) isReqAccountSpecified_Value() {}
func (*ReqAccountSpecified_Male) isReqAccountSpecified_Value()           {}
func (*ReqAccountSpecified_Married) isReqAccountSpecified_Value()        {}

func (m *ReqAccountSpecified) GetValue() isReqAccountSpecified_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ReqAccountSpecified) GetGreaterThan() int32 {
	if x, ok := m.GetValue().(*ReqAccountSpecified_GreaterThan); ok {
		return x.GreaterThan
	}
	return 0
}

func (m *ReqAccountSpecified) GetNotgreaterThan() int32 {
	if x, ok := m.GetValue().(*ReqAccountSpecified_NotgreaterThan); ok {
		return x.NotgreaterThan
	}
	return 0
}

func (m *ReqAccountSpecified) GetMale() bool {
	if x, ok := m.GetValue().(*ReqAccountSpecified_Male); ok {
		return x.Male
	}
	return false
}

func (m *ReqAccountSpecified) GetMarried() bool {
	if x, ok := m.GetValue().(*ReqAccountSpecified_Married); ok {
		return x.Married
	}
	return false
}

func (m *ReqAccountSpecified) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReqAccountSpecified) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReqAccountSpecified_OneofMarshaler, _ReqAccountSpecified_OneofUnmarshaler, _ReqAccountSpecified_OneofSizer, []interface{}{
		(*ReqAccountSpecified_GreaterThan)(nil),
		(*ReqAccountSpecified_NotgreaterThan)(nil),
		(*ReqAccountSpecified_Male)(nil),
		(*ReqAccountSpecified_Married)(nil),
	}
}

func _ReqAccountSpecified_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReqAccountSpecified)
	// value
	switch x := m.Value.(type) {
	case *ReqAccountSpecified_GreaterThan:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.GreaterThan))
	case *ReqAccountSpecified_NotgreaterThan:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.NotgreaterThan))
	case *ReqAccountSpecified_Male:
		t := uint64(0)
		if x.Male {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *ReqAccountSpecified_Married:
		t := uint64(0)
		if x.Married {
			t = 1
		}
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("ReqAccountSpecified.Value has unexpected type %T", x)
	}
	return nil
}

func _ReqAccountSpecified_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReqAccountSpecified)
	switch tag {
	case 1: // value.greaterThan
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &ReqAccountSpecified_GreaterThan{int32(x)}
		return true, err
	case 2: // value.notgreaterThan
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &ReqAccountSpecified_NotgreaterThan{int32(x)}
		return true, err
	case 3: // value.male
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &ReqAccountSpecified_Male{x != 0}
		return true, err
	case 4: // value.married
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &ReqAccountSpecified_Married{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _ReqAccountSpecified_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReqAccountSpecified)
	// value
	switch x := m.Value.(type) {
	case *ReqAccountSpecified_GreaterThan:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.GreaterThan))
	case *ReqAccountSpecified_NotgreaterThan:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.NotgreaterThan))
	case *ReqAccountSpecified_Male:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += 1
	case *ReqAccountSpecified_Married:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResAccountsSelfIntro struct {
	Accouts []string `protobuf:"bytes,1,rep,name=accouts" json:"accouts,omitempty"`
}

func (m *ResAccountsSelfIntro) Reset()                    { *m = ResAccountsSelfIntro{} }
func (m *ResAccountsSelfIntro) String() string            { return proto.CompactTextString(m) }
func (*ResAccountsSelfIntro) ProtoMessage()               {}
func (*ResAccountsSelfIntro) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ResAccountsSelfIntro) GetAccouts() []string {
	if m != nil {
		return m.Accouts
	}
	return nil
}

func init() {
	proto.RegisterType((*Hellochain33Action)(nil), "types.Hellochain33Action")
	proto.RegisterType((*SetSelfIntroAction)(nil), "types.SetSelfIntroAction")
	proto.RegisterType((*LogSetSelfIntro)(nil), "types.logSetSelfIntro")
	proto.RegisterType((*PingPongAction)(nil), "types.PingPongAction")
	proto.RegisterType((*LogPingPong)(nil), "types.logPingPong")
	proto.RegisterType((*SelfIntroInfo)(nil), "types.SelfIntroInfo")
	proto.RegisterType((*PingPongStatus)(nil), "types.PingPongStatus")
	proto.RegisterType((*ReqPingPongStatus)(nil), "types.ReqPingPongStatus")
	proto.RegisterType((*PingPongCount)(nil), "types.PingPongCount")
	proto.RegisterType((*ReqAccount)(nil), "types.ReqAccount")
	proto.RegisterType((*ReqAccountSpecified)(nil), "types.ReqAccountSpecified")
	proto.RegisterType((*ResAccountsSelfIntro)(nil), "types.ResAccountsSelfIntro")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hellochain33 service

type Hellochain33Client interface {
	// 获取指定账户的个人介绍信息
	GetSelfIntro(ctx context.Context, in *ReqAccount, opts ...grpc.CallOption) (*SelfIntroInfo, error)
	// 获取指定账户的ping，pong状态
	GetPingPongStatus(ctx context.Context, in *ReqAccount, opts ...grpc.CallOption) (*PingPongStatus, error)
	// 获取所有满足条件的用户
	GetAccountsSelfIntroSetted(ctx context.Context, in *ReqAccountSpecified, opts ...grpc.CallOption) (*ResAccountsSelfIntro, error)
	// 获取处在ping或pong的状态下的用户数
	GetPingOrPongs(ctx context.Context, in *ReqPingPongStatus, opts ...grpc.CallOption) (*PingPongCount, error)
}

type hellochain33Client struct {
	cc *grpc.ClientConn
}

func NewHellochain33Client(cc *grpc.ClientConn) Hellochain33Client {
	return &hellochain33Client{cc}
}

func (c *hellochain33Client) GetSelfIntro(ctx context.Context, in *ReqAccount, opts ...grpc.CallOption) (*SelfIntroInfo, error) {
	out := new(SelfIntroInfo)
	err := grpc.Invoke(ctx, "/types.hellochain33/GetSelfIntro", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hellochain33Client) GetPingPongStatus(ctx context.Context, in *ReqAccount, opts ...grpc.CallOption) (*PingPongStatus, error) {
	out := new(PingPongStatus)
	err := grpc.Invoke(ctx, "/types.hellochain33/GetPingPongStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hellochain33Client) GetAccountsSelfIntroSetted(ctx context.Context, in *ReqAccountSpecified, opts ...grpc.CallOption) (*ResAccountsSelfIntro, error) {
	out := new(ResAccountsSelfIntro)
	err := grpc.Invoke(ctx, "/types.hellochain33/GetAccountsSelfIntroSetted", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hellochain33Client) GetPingOrPongs(ctx context.Context, in *ReqPingPongStatus, opts ...grpc.CallOption) (*PingPongCount, error) {
	out := new(PingPongCount)
	err := grpc.Invoke(ctx, "/types.hellochain33/GetPingOrPongs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hellochain33 service

type Hellochain33Server interface {
	// 获取指定账户的个人介绍信息
	GetSelfIntro(context.Context, *ReqAccount) (*SelfIntroInfo, error)
	// 获取指定账户的ping，pong状态
	GetPingPongStatus(context.Context, *ReqAccount) (*PingPongStatus, error)
	// 获取所有满足条件的用户
	GetAccountsSelfIntroSetted(context.Context, *ReqAccountSpecified) (*ResAccountsSelfIntro, error)
	// 获取处在ping或pong的状态下的用户数
	GetPingOrPongs(context.Context, *ReqPingPongStatus) (*PingPongCount, error)
}

func RegisterHellochain33Server(s *grpc.Server, srv Hellochain33Server) {
	s.RegisterService(&_Hellochain33_serviceDesc, srv)
}

func _Hellochain33_GetSelfIntro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Hellochain33Server).GetSelfIntro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.hellochain33/GetSelfIntro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Hellochain33Server).GetSelfIntro(ctx, req.(*ReqAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hellochain33_GetPingPongStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Hellochain33Server).GetPingPongStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.hellochain33/GetPingPongStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Hellochain33Server).GetPingPongStatus(ctx, req.(*ReqAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hellochain33_GetAccountsSelfIntroSetted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAccountSpecified)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Hellochain33Server).GetAccountsSelfIntroSetted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.hellochain33/GetAccountsSelfIntroSetted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Hellochain33Server).GetAccountsSelfIntroSetted(ctx, req.(*ReqAccountSpecified))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hellochain33_GetPingOrPongs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPingPongStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Hellochain33Server).GetPingOrPongs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.hellochain33/GetPingOrPongs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Hellochain33Server).GetPingOrPongs(ctx, req.(*ReqPingPongStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hellochain33_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.hellochain33",
	HandlerType: (*Hellochain33Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSelfIntro",
			Handler:    _Hellochain33_GetSelfIntro_Handler,
		},
		{
			MethodName: "GetPingPongStatus",
			Handler:    _Hellochain33_GetPingPongStatus_Handler,
		},
		{
			MethodName: "GetAccountsSelfIntroSetted",
			Handler:    _Hellochain33_GetAccountsSelfIntroSetted_Handler,
		},
		{
			MethodName: "GetPingOrPongs",
			Handler:    _Hellochain33_GetPingOrPongs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hellochain33.proto",
}

func init() { proto.RegisterFile("hellochain33.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xb5, 0x9d, 0xb8, 0x09, 0x93, 0x34, 0x90, 0x21, 0x20, 0x13, 0x2e, 0xd5, 0x4a, 0xa0, 0x48,
	0x48, 0x01, 0x1a, 0x71, 0xe0, 0x54, 0x5a, 0x0e, 0x49, 0x4f, 0x54, 0x1b, 0x24, 0xce, 0xc6, 0xd9,
	0x38, 0x96, 0x5c, 0x6f, 0x6a, 0xaf, 0x2b, 0xe5, 0x03, 0xb8, 0x22, 0xf1, 0x0d, 0x1c, 0xb8, 0xf1,
	0x8d, 0xc8, 0xeb, 0xf5, 0xda, 0x8e, 0x13, 0x8e, 0xbd, 0xed, 0x8c, 0xe7, 0xed, 0xbe, 0xf7, 0x66,
	0xc6, 0x80, 0x1b, 0x16, 0x86, 0xdc, 0xdb, 0xb8, 0x41, 0x34, 0x9b, 0x4d, 0xb7, 0x31, 0x17, 0x1c,
	0x6d, 0xb1, 0xdb, 0xb2, 0x84, 0xfc, 0x36, 0x01, 0x17, 0x95, 0xaf, 0x97, 0x9e, 0x08, 0x78, 0x84,
	0x17, 0xd0, 0x5f, 0x32, 0xb1, 0x64, 0xe1, 0xfa, 0x3a, 0x12, 0x31, 0x77, 0xcc, 0x33, 0x73, 0xd2,
	0x3b, 0x7f, 0x31, 0x95, 0xa0, 0x69, 0xf5, 0x53, 0x0e, 0x58, 0x18, 0xb4, 0x06, 0xc0, 0x19, 0x74,
	0x6f, 0x82, 0xc8, 0xbf, 0xe1, 0x91, 0xef, 0x58, 0x12, 0xfc, 0x4c, 0x81, 0x8b, 0xb4, 0x06, 0xea,
	0x42, 0x1c, 0x80, 0x25, 0x76, 0x4e, 0xeb, 0xcc, 0x9c, 0xd8, 0xd4, 0x12, 0xbb, 0xab, 0x0e, 0xd8,
	0xf7, 0x6e, 0x98, 0x32, 0xf2, 0xd3, 0x04, 0x6c, 0x3e, 0x8a, 0x04, 0xfa, 0x41, 0x16, 0xae, 0x52,
	0x19, 0x4b, 0x96, 0x8f, 0x68, 0x2d, 0x87, 0x4f, 0xa0, 0xe5, 0xfa, 0x4c, 0x72, 0xb0, 0x69, 0x76,
	0x44, 0x84, 0xf6, 0xad, 0x1b, 0x32, 0xf9, 0x4e, 0x97, 0xca, 0x33, 0x3a, 0xd0, 0xb9, 0x75, 0xe3,
	0x38, 0x60, 0x2b, 0xa7, 0x2d, 0xd3, 0x45, 0x88, 0x23, 0xb0, 0x23, 0x2e, 0x58, 0xe2, 0xd8, 0xf2,
	0xf2, 0x3c, 0x20, 0xbf, 0x4c, 0x78, 0x1c, 0x72, 0xbf, 0x26, 0x19, 0xa1, 0xed, 0xae, 0x56, 0xb1,
	0x62, 0x21, 0xcf, 0xf8, 0x01, 0xba, 0xdb, 0x98, 0xdd, 0x07, 0x3c, 0x4d, 0x94, 0x0d, 0xc7, 0x3d,
	0xa4, 0xba, 0x14, 0x67, 0xd0, 0xf1, 0xd2, 0x38, 0x66, 0x91, 0x90, 0x2c, 0xff, 0x8b, 0x2a, 0x2a,
	0xc9, 0x27, 0x18, 0xd4, 0xbd, 0xcd, 0x54, 0xb9, 0x9e, 0xc7, 0xd3, 0x48, 0x28, 0x52, 0x45, 0x58,
	0xaa, 0xb2, 0xaa, 0xaa, 0x7e, 0x98, 0xd0, 0x0b, 0xb9, 0xaf, 0xfb, 0x71, 0x48, 0xd1, 0xfb, 0x86,
	0xa2, 0xfd, 0xc6, 0x2e, 0x85, 0x2b, 0xd2, 0xa4, 0xa2, 0xe6, 0xed, 0xbe, 0x9a, 0x23, 0x08, 0xad,
	0x24, 0x81, 0x53, 0xad, 0xf2, 0x3a, 0x5a, 0xf3, 0x87, 0x68, 0x34, 0x99, 0x94, 0xf6, 0xe5, 0x7c,
	0xf0, 0x39, 0x9c, 0x24, 0xf2, 0x24, 0xdf, 0xeb, 0x52, 0x15, 0x91, 0x37, 0x30, 0xa4, 0xec, 0xee,
	0x68, 0xb1, 0x55, 0x2b, 0x7e, 0x05, 0xa7, 0x45, 0xe5, 0xe7, 0xc2, 0xfa, 0xb2, 0x25, 0x36, 0xcd,
	0x03, 0xf2, 0x1a, 0x80, 0xb2, 0xbb, 0x4b, 0xd5, 0x9e, 0xa3, 0x8d, 0x23, 0x7f, 0x4d, 0x78, 0x5a,
	0x16, 0x2e, 0xb7, 0xcc, 0x0b, 0xd6, 0xd9, 0x98, 0x12, 0xe8, 0xf9, 0x31, 0x73, 0x05, 0x8b, 0xbf,
	0x6e, 0xdc, 0xdc, 0x20, 0x7b, 0x61, 0xd0, 0x6a, 0x12, 0x27, 0x30, 0x88, 0xb8, 0xa8, 0x96, 0x59,
	0xaa, 0x6c, 0x2f, 0x8f, 0xa3, 0xaa, 0x73, 0x0b, 0x43, 0x79, 0x37, 0xde, 0xf3, 0x6e, 0x61, 0x94,
	0x6b, 0x92, 0xaf, 0xae, 0xdd, 0x5c, 0xdd, 0x77, 0x30, 0xa2, 0x2c, 0x51, 0x7c, 0x93, 0x72, 0x5b,
	0x0a, 0x89, 0x22, 0x73, 0xb7, 0xa5, 0x25, 0x8a, 0xe4, 0xfc, 0x8f, 0x05, 0xfd, 0xea, 0x0f, 0x0b,
	0x3f, 0x42, 0x7f, 0x5e, 0x5d, 0xb4, 0xa1, 0x1a, 0x9f, 0xd2, 0x87, 0xf1, 0x48, 0xef, 0x47, 0x65,
	0x6c, 0x88, 0x81, 0x17, 0x30, 0x9c, 0x33, 0xb1, 0xd7, 0xaa, 0x03, 0xf8, 0xc3, 0x13, 0x49, 0x0c,
	0xfc, 0x06, 0xe3, 0x39, 0x13, 0x0d, 0xfa, 0x4b, 0x26, 0x04, 0x5b, 0xe1, 0xb8, 0x71, 0x93, 0xee,
	0xc8, 0xf8, 0xa5, 0xfe, 0xd6, 0x54, 0x4f, 0x0c, 0xbc, 0x82, 0x81, 0x62, 0xf6, 0x25, 0xce, 0x5e,
	0x4c, 0xd0, 0x29, 0x2f, 0xab, 0xd3, 0xd0, 0xea, 0x6a, 0x83, 0x44, 0x8c, 0xef, 0x27, 0xf2, 0x57,
	0x3e, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x86, 0x7c, 0x5a, 0xe0, 0x05, 0x00, 0x00,
}
